# -*- coding: utf-8 -*-
"""motarjimi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y8PEm1mAT2Q1l602wPKQ-Z0pO0szAOvh
"""

import logging
from telegram import Update
from telegram.ext import Updater, CommandHandler, MessageHandler, CallbackContext, Filters
from googletrans import Translator

# Set up logging
logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s', level=logging.INFO)
logger = logging.getLogger(__name__)

# Initialize translator once
translator = Translator()

# Define the start command
def start(update: Update, context: CallbackContext) -> None:
    welcome_message = "مرحباً بك في بوت المترجم! أرسل لي أي نص وسأترجمه إلى العربية."
    emojis = "🌟✨😊"
    update.message.reply_text(f'{emojis} {welcome_message} {emojis}')

# Define the translate function using Google Translate API
def translate_text_google(update: Update, context: CallbackContext) -> None:
    text_to_translate = update.message.text
    translation = translate_text_google_api(text_to_translate)
    update.message.reply_text(f'{translation}')

# Function to translate text using Google Translate API
def translate_text_google_api(text, target_language='ar'):
    translation = translator.translate(text, dest=target_language)
    return translation.text

# Define the help command
def help_command(update: Update, context: CallbackContext) -> None:
    help_text = "إذا كنت بحاجة إلى مساعدة، يرجى التواصل معي على Instagram: @yzuun "
    update.message.reply_text(help_text)

# ... (rest of the code)

# Define the main function to handle messages
def main() -> None:
    # Replace 'YOUR_API_TOKEN' with your actual Telegram Bot API token
    api_token = '6614311224:AAH5NBWpcu7Q0zdT_IpWdGIX4sZuwTxaI98'

    if api_token is None or api_token == '':
        raise ValueError("Telegram API token not provided. Set the TELEGRAM_API_TOKEN environment variable or replace 'YOUR_API_TOKEN' with the actual token.")

    updater = Updater(token=api_token)

    dp = updater.dispatcher

    dp.add_handler(CommandHandler("start", start))
    dp.add_handler(CommandHandler("help", help_command))
    dp.add_handler(MessageHandler(Filters.text & ~Filters.command, translate_text_google))

    updater.start_polling()

    updater.idle()

if __name__ == '__main__':
    main()

pip install SpeechRecognition

pip install google-cloud

pip install pytesseract pillow

pip install googletrans==4.0.0-rc1



pip install python-telegram-bot==13.15

pip install python-telegram-bot

pip install translate